import type { NextPage } from "next"
import Head from "next/head"

import HeaderCom from "../../components/FixedElement/SubHeader/HeaderCom"
import FooterCom from "../../components/FixedElement/FooterCom"
import { Layout } from "../../components/FixedElement/Layout"

import { MonthCalenderCom } from "../../components/Organisms/MonthCalendarCom"
import { HeaderNavi } from "components/FixedElement/MainHeader/HeaderNavi"

const Date = [
  { Regular: "深良元旦", Day: 1, Venue: "日", Hour: 0, Minute: "00" },
  { Day: 5, Venue: "木", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 7, Venue: "土", Hour: 9, Minute: "00" },
  { Day: 12, Venue: "木", Hour: 17, Minute: 30 },
  { Day: 13, Venue: "金", Hour: 17, Minute: 30 },
  { Regular: "裾野駅伝", Day: 15, Venue: "日", Hour: 0, Minute: "00" },
  { Day: 17, Venue: "火", Hour: 17, Minute: 30 },
  { Day: 19, Venue: "木", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 21, Venue: "土", Hour: 9, Minute: "00" },
  { Regular: "駅伝", Day: 22, Venue: "日", Hour: 9, Minute: "00" },
  { Day: 24, Venue: "火", Hour: 17, Minute: 30 },
  { Day: 26, Venue: "木", Hour: 17, Minute: 30 },
  { Day: 27, Venue: "金", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 28, Venue: "土", Hour: 9, Minute: "00" },
  { Day: 31, Venue: "火", Hour: 17, Minute: 30 },
]

const Calender1: NextPage = () => {
  return (
    <>
      <Layout title="1月練習予定">
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeaderNavi />
        <HeaderCom Color="" Caption="1月練習予定" />
        <MonthCalenderCom CALENDER_ITEMS={Date} />
        <FooterCom />
      </Layout>
    </>
  )
}

export default Calender1
