import type { NextPage } from 'next'
import Head from 'next/head'

import HeaderCom from '../../components/FixedElement/HeaderCom'
import FooterCom from '../../components/FixedElement/FooterCom'
import { Layout } from '../../components/FixedElement/Layout'

import Calender from '../../components/Organisms/CalendarCom'

const Date = [
  { Day: 2, Hour: 17, Minute: 30, Venue: '火' },
  { Day: 3, Hour: 18, Minute: '00', Venue: '水' },
  { Day: 5, Hour: 18, Minute: '00', Venue: '金' },
  { Day: 9, Hour: 17, Minute: 30, Venue: '火' },
  { Day: 11, Hour: 16, Minute: '00', Venue: '木(不二聖心)' },
  { Day: 13, Hour: 18, Minute: '00', Venue: '土' },
  { Day: 16, Hour: 17, Minute: 30, Venue: '火' },
  { Day: 18, Hour: 16, Minute: '00', Venue: '木(不二聖心)' },
  { Day: 19, Hour: 18, Minute: '00', Venue: '金' },
  { Day: 20, Hour: 18, Minute: '00', Venue: '土' },
  { Day: 23, Hour: 17, Minute: 30, Venue: '火' },
  { Day: 25, Hour: 16, Minute: '00', Venue: '木(不二聖心)' },
  { Day: 26, Hour: 18, Minute: '00', Venue: '金' },
  { Day: 27, Hour: 18, Minute: '00', Venue: '土' },
  { Day: 29, Hour: 17, Minute: 30, Venue: '火' },
]

const Calender08: NextPage = () => {
  return (
    <>
      <Layout title="８月練習予定">
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeaderCom Color="" Caption="８月練習予定" />
        <Calender CALENDER_ITEMS={Date} />
        <FooterCom />
      </Layout>
    </>
  )
}

export default Calender08
