import type { NextPage } from "next"
import Head from "next/head"

import HeaderCom from "../../components/FixedElement/SubHeader/HeaderCom"
import FooterCom from "../../components/FixedElement/FooterCom"
import { Layout } from "../../components/FixedElement/Layout"

import { MonthCalenderCom } from "../../components/Organisms/MonthCalendarCom"
import { HeaderNavi } from "components/FixedElement/MainHeader/HeaderNavi"

const Date = [
  { Day: 1, Venue: "金", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 2, Venue: "土", Hour: 18, Minute: "00" },
  { Day: 5, Venue: "火", Hour: 17, Minute: 30 },
  { Day: 7, Venue: "木", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 9, Venue: "土", Hour: 9, Minute: "00" },
  { Day: 12, Venue: "火", Hour: 17, Minute: 30 },
  { Day: 14, Venue: "木", Hour: 17, Minute: 30 },
  { Day: 15, Venue: "金", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 16, Venue: "土", Hour: 18, Minute: "00" },
  { Regular: "全国大会", Day: 16, Venue: "土", Hour: 7, Minute: "00" },
  { Regular: "定期", Day: 21, Venue: "木", Hour: 18, Minute: "00" },
  { Regular: "三島市陸上記録会", Day: 23, Venue: "土", Hour: 7, Minute: "00" },
  { Day: 26, Venue: "火", Hour: 17, Minute: 30 },
  { Day: 28, Venue: "木", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 29, Venue: "金", Hour: 18, Minute: "00" },
]

const Calender9: NextPage = () => {
  return (
    <>
      <Layout title="9月練習予定">
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeaderNavi />
        <HeaderCom Color="" Caption="9月練習予定" />
        <MonthCalenderCom CALENDER_ITEMS={Date} />
        <FooterCom />
      </Layout>
    </>
  )
}

export default Calender9
