import type { NextPage } from "next"
import Head from "next/head"

import HeaderCom from "../../components/FixedElement/SubHeader/HeaderCom"
import FooterCom from "../../components/FixedElement/FooterCom"
import { Layout } from "../../components/FixedElement/Layout"

import { MonthCalenderCom } from "../../components/Organisms/MonthCalendarCom"
import { HeaderNavi } from "components/FixedElement/MainHeader/HeaderNavi"

const Date = [
  { Regular: "定期", Day: 2, Venue: "水", Hour: 18, Minute: "00" },
  { Day: 8, Venue: "火", Hour: 17, Minute: 30 },
  { Day: 10, Venue: "木", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 12, Venue: "土", Hour: 9, Minute: "00" },
  { Day: 15, Venue: "火", Hour: 17, Minute: 30 },
  { Day: 17, Venue: "木", Hour: 17, Minute: 30 },
  { Day: 18, Venue: "金", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 19, Venue: "土", Hour: 18, Minute: "00" },
  { Day: 22, Venue: "火", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 24, Venue: "木", Hour: 18, Minute: "00" },
  { Regular: "東海大会", Day: 26, Venue: "土", Hour: 7, Minute: "00" },
  { Day: 29, Venue: "火", Hour: 17, Minute: 30 },
  { Day: 31, Venue: "木", Hour: 17, Minute: 30 },
]

const Calender8: NextPage = () => {
  return (
    <>
      <Layout title="8月練習予定">
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeaderNavi />
        <HeaderCom Color="" Caption="8月練習予定" />
        <MonthCalenderCom CALENDER_ITEMS={Date} />
        <FooterCom />
      </Layout>
    </>
  )
}

export default Calender8
