import type { NextPage } from 'next'
import Head from 'next/head'

import HeaderCom from '../../components/FixedElement/HeaderCom'
import FooterCom from '../../components/FixedElement/FooterCom'
import { Layout } from '../../components/FixedElement/Layout'

import Calender from '../../components/Organisms/CalendarCom'

const Date = [
  { Day: 5, Hour: 17, Minute: 30, Venue: '火' },
  { Day: 7, Hour: 17, Minute: 30, Venue: '木' },
  { Day: 8, Hour: 18, Minute: '00', Venue: '金' },
  { Day: 12, Hour: 17, Minute: 30, Venue: '火' },
  { Day: 14, Hour: 18, Minute: '00', Venue: '木' },
  { Day: 15, Hour: 17, Minute: 30, Venue: '金' },
  { Day: 16, Hour: 7, Minute: '00', Venue: '富士裾野トラックミート' },
  { Day: 21, Hour: 17, Minute: 30, Venue: '木' },
  { Day: 22, Hour: 17, Minute: 30, Venue: '金' },
  { Day: 23, Hour: 18, Minute: '00', Venue: '土' },
  { Day: 26, Hour: 17, Minute: 30, Venue: '火' },
  { Day: 28, Hour: 18, Minute: '00', Venue: '木' },
  { Day: 30, Hour: 0, Minute: 0, Venue: '東部陸上カーニバル' },
]

const Calender07: NextPage = () => {
  return (
    <>
      <Layout title="７月練習予定">
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeaderCom Color="" Caption="7月練習予定" />
        <Calender CALENDER_ITEMS={Date} />
        <FooterCom />
      </Layout>
    </>
  )
}

export default Calender07
