import type { NextPage } from 'next'
import Head from 'next/head'

import HeaderCom from '../../components/FixedElement/HeaderCom'
import FooterCom from '../../components/FixedElement/FooterCom'
import { Layout } from '../../components/FixedElement/Layout'

import Calender from '../../components/Organisms/CalendarCom'

const Date = [{ Day: 1, Hour: 18, Minute: '00', Venue: '競技場' }]

const Calender08: NextPage = () => {
  return (
    <>
      <Layout title="８月練習予定">
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeaderCom />
        <Calender CALENDER_ITEMS={Date} />
      </Layout>
      <FooterCom />
    </>
  )
}

export default Calender08
