import type { NextPage } from "next"
import Head from "next/head"

import HeaderCom from "../../components/FixedElement/SubHeader/HeaderCom"
import FooterCom from "../../components/FixedElement/FooterCom"
import { Layout } from "../../components/FixedElement/Layout"

import { MonthCalenderCom } from "../../components/Organisms/MonthCalendarCom"
import { HeaderNavi } from "components/FixedElement/MainHeader/HeaderNavi"

const Date = [
  { Regular: "県交流大会", Day: 1, Hour: 7, Minute: "00", Venue: "土" },
  { Day: 4, Hour: 17, Minute: 30, Venue: "火" },
  { Day: 6, Hour: 17, Minute: 30, Venue: "木" },
  { Day: 7, Hour: 17, Minute: 30, Venue: "金" },
  { Regular: "定期", Day: 8, Hour: 18, Minute: "00", Venue: "土" },
  { Day: 11, Hour: 17, Minute: 30, Venue: "火" },
  { Regular: "定期", Day: 13, Hour: 18, Minute: "00", Venue: "木" },
  {
    Regular: "富士裾野トラックミート",
    Day: 15,
    Hour: 7,
    Minute: "00",
    Venue: "土",
  },
  { Day: 18, Hour: 17, Minute: 30, Venue: "火" },
  { Day: 20, Hour: 17, Minute: 30, Venue: "木" },
  { Day: 21, Hour: 17, Minute: 30, Venue: "金" },
  { Regular: "定期", Day: 22, Hour: 9, Minute: "00", Venue: "土" },
  { Day: 25, Hour: 17, Minute: 30, Venue: "火" },
  { Day: 26, Venue: "水", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 27, Hour: 18, Minute: "00", Venue: "木" },
  {
    Regular: "東部陸上カーニバル",
    Day: 29,
    Hour: 9,
    Minute: "00",
    Venue: "土",
  },
]

const Calender7: NextPage = () => {
  return (
    <>
      <Layout title="7月練習予定">
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeaderNavi />
        <HeaderCom Color="" Caption="7月練習予定" />
        <MonthCalenderCom CALENDER_ITEMS={Date} />
        <FooterCom />
      </Layout>
    </>
  )
}

export default Calender7
