import type { NextPage } from "next"
import Head from "next/head"

import HeaderCom from "../../components/FixedElement/SubHeader/HeaderCom"
import FooterCom from "../../components/FixedElement/FooterCom"
import { Layout } from "../../components/FixedElement/Layout"

import { MonthCalenderCom } from "../../components/Organisms/MonthCalendarCom"
import { HeaderNavi } from "components/FixedElement/MainHeader/HeaderNavi"

const Date = [
  { Regular: "定期", Day: 2, Venue: "木", Hour: 18, Minute: "00" },
  { Day: 7, Venue: "火", Hour: 17, Minute: 30 },
  { Day: 9, Venue: "木", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 11, Venue: "土", Hour: 9, Minute: "00" },
  { Day: 14, Venue: "火", Hour: 17, Minute: 30 },
  { Day: 16, Venue: "木", Hour: 17, Minute: 30 },
  { Day: 17, Venue: "金", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 18, Venue: "土", Hour: 9, Minute: "00" },
  { Day: 21, Venue: "火", Hour: 17, Minute: 30 },
  { Day: 23, Venue: "木", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 25, Venue: "土", Hour: 9, Minute: "00" },
  { Day: 28, Venue: "火", Hour: 17, Minute: 30 },
  { Day: 30, Venue: "木", Hour: 17, Minute: 30 },
]

const Calender11: NextPage = () => {
  return (
    <>
      <Layout title="11月練習予定">
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeaderNavi />
        <HeaderCom Color="" Caption="11月練習予定" />
        <MonthCalenderCom CALENDER_ITEMS={Date} />
        <FooterCom />
      </Layout>
    </>
  )
}

export default Calender11
