import type { NextPage } from "next"
import Head from "next/head"

import HeaderCom from "../../components/FixedElement/SubHeader/HeaderCom"
import FooterCom from "../../components/FixedElement/FooterCom"
import { Layout } from "../../components/FixedElement/Layout"

import { MonthCalenderCom } from "../../components/Organisms/MonthCalendarCom"
import { HeaderNavi } from "components/FixedElement/MainHeader/HeaderNavi"

const Date = [
  { Day: 1, Venue: "木", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 3, Venue: "土", Hour: 18, Minute: "00" },
  { Day: 6, Venue: "火", Hour: 17, Minute: 30 },
  { Day: 8, Venue: "木", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 9, Venue: "金", Hour: 18, Minute: "00" },
  { Regular: "チャレンジカップ", Day: 11, Venue: "日", Hour: 7, Minute: "00" },
  { Day: 13, Venue: "火", Hour: 17, Minute: 30 },
  { Day: 15, Venue: "木", Hour: 17, Minute: 30 },
  { Day: 16, Venue: "金", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 17, Venue: "土", Hour: 18, Minute: "00" },
  { Day: 20, Venue: "火", Hour: 17, Minute: 30 },
  { Day: 22, Venue: "木", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 24, Venue: "土", Hour: 9, Minute: "00" },
  { Day: 27, Venue: "火", Hour: 17, Minute: 30 },
  { Day: 28, Venue: "水", Hour: 17, Minute: 30 },
  { Regular: "定期", Day: 29, Venue: "木", Hour: 18, Minute: "00" },
]

const Calender6: NextPage = () => {
  return (
    <>
      <Layout title="6月練習予定">
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeaderNavi />
        <HeaderCom Color="" Caption="6月練習予定" />
        <MonthCalenderCom CALENDER_ITEMS={Date} />
        <FooterCom />
      </Layout>
    </>
  )
}

export default Calender6
