import type { NextPage } from 'next'
import Head from 'next/head'

import HeaderCom from '../components/FixedElement/HeaderCom'
import FooterCom from '../components/FixedElement/FooterCom'
import { Layout } from '../components/FixedElement/Layout'

import IndexCom from 'components/Organisms/IndexCom'

const Home: NextPage = () => {
  return (
    <>
      <Layout title="裾野市陸上教室">
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeaderCom />
        <IndexCom />
      </Layout>
      <FooterCom />
    </>
  )
}

export default Home
